-- =============================================================
-- PHARMA SUPPLY CHAIN ML SYSTEM — MYSQL SCHEMA
-- =============================================================
-- Category Legend:
--   [INPUT]          Static master data, written once
--   [INPUT-ROLLING]  Grows daily with new data
--   [DERIVED]        Computed from demand_history periodically
--   [OUTPUT]         Generated by ML pipeline each daily run
-- =============================================================

CREATE DATABASE IF NOT EXISTS pharma_sc
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE pharma_sc;

-- =============================================================
-- [INPUT] 1. sku_master
-- Core product master. No category_share here (see sku_market_share_monthly).
-- =============================================================
CREATE TABLE sku_master (
    id                        BIGINT        NOT NULL AUTO_INCREMENT,
    sku_id                    VARCHAR(20)   NOT NULL COMMENT 'e.g. M01AB-01',
    brand_name                VARCHAR(100)  NOT NULL COMMENT 'e.g. Inflamac',
    atc_code                  VARCHAR(10)   NOT NULL COMMENT 'e.g. M01AB',
    manufacturer              VARCHAR(100)  NOT NULL COMMENT 'e.g. Cipla Ltd',
    regulatory_class          VARCHAR(30)   NOT NULL COMMENT 'Schedule H | Schedule H1 | OTC',
    hsn_code                  VARCHAR(20)            COMMENT 'Indian HSN code for GST',
    nlem_listed               BOOLEAN       NOT NULL DEFAULT FALSE COMMENT 'National List of Essential Medicines',
    criticality               VARCHAR(20)   NOT NULL COMMENT 'critical | high | standard | low',
    criticality_rationale     VARCHAR(300)           COMMENT 'Business reason for this classification',
    criticality_reviewed_on   DATE                   COMMENT 'Last SOP review date',
    criticality_reviewed_by   VARCHAR(100)           COMMENT 'e.g. supply_chain_committee@pharma.in',
    unit_cost_inr             INT           NOT NULL COMMENT 'Current unit cost (see sku_cost_history for full timeline)',
    shelf_life_days           INT           NOT NULL COMMENT 'Approved shelf life in days',
    created_at                TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (id),
    UNIQUE KEY uq_sku_id (sku_id),
    INDEX idx_atc_code (atc_code),
    INDEX idx_criticality (criticality)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Product master — one row per SKU';


-- =============================================================
-- [INPUT] 2. locations
-- Warehouse / DC master. No demand_share here (see location_demand_summary).
-- =============================================================
CREATE TABLE locations (
    id              BIGINT       NOT NULL AUTO_INCREMENT,
    location_id     VARCHAR(30)  NOT NULL COMMENT 'e.g. DC_MUMBAI',
    name            VARCHAR(100) NOT NULL COMMENT 'e.g. Mumbai Metro DC',
    type            VARCHAR(30)  NOT NULL COMMENT 'metro_dc | tier2_wh',
    capacity_units  INT          NOT NULL DEFAULT 0,
    city            VARCHAR(80)            COMMENT 'e.g. Mumbai',
    state           VARCHAR(80)            COMMENT 'e.g. Maharashtra',
    pincode         VARCHAR(10),
    gstin           VARCHAR(20)            COMMENT 'GST registration number',
    commissioned_on DATE                   COMMENT 'When this location went live',
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (id),
    UNIQUE KEY uq_location_id (location_id),
    INDEX idx_type (type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Warehouse and DC master';


-- =============================================================
-- [INPUT] 3. lanes
-- Supply lanes: SUPPLIER→location (replenish) or DC→WH (transfer)
-- =============================================================
CREATE TABLE lanes (
    id              BIGINT      NOT NULL AUTO_INCREMENT,
    from_location   VARCHAR(30) NOT NULL COMMENT 'SUPPLIER or a location_id',
    to_location     VARCHAR(30) NOT NULL COMMENT 'FK → locations.location_id',
    mode            VARCHAR(20) NOT NULL COMMENT 'replenish | transfer',
    lead_time_days  INT         NOT NULL,
    carrier         VARCHAR(100)         COMMENT 'e.g. Blue Dart, TCI',
    created_at      TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (id),
    UNIQUE KEY uq_lane (from_location, to_location, mode),
    INDEX idx_to_location (to_location),
    INDEX idx_mode (mode)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Logistics lanes between nodes';


-- =============================================================
-- [INPUT] 4. distributors
-- One distributor per location/region.
-- =============================================================
CREATE TABLE distributors (
    id                  BIGINT      NOT NULL AUTO_INCREMENT,
    distributor_id      VARCHAR(30) NOT NULL COMMENT 'e.g. DST_DC_MUMBAI',
    region              VARCHAR(30) NOT NULL COMMENT 'FK → locations.location_id',
    distributor_name    VARCHAR(150)         COMMENT 'e.g. Mumbai MedSupply Pvt Ltd',
    order_cycle_days    INT         NOT NULL COMMENT 'Average days between orders',
    order_size_sigma    DECIMAL(5,3) NOT NULL COMMENT 'Order sizing noise sigma',
    contact_email       VARCHAR(150),
    created_at          TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (id),
    UNIQUE KEY uq_distributor_id (distributor_id),
    INDEX idx_region (region)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Distributor master per region';


-- =============================================================
-- [INPUT] 5. promo_calendar
-- Marketing promotions. Past promos show actual vs planned uplift.
-- =============================================================
CREATE TABLE promo_calendar (
    id                  BIGINT       NOT NULL AUTO_INCREMENT,
    promo_id            VARCHAR(30)  NOT NULL COMMENT 'e.g. PRM_WINTER_2018',
    name                VARCHAR(100) NOT NULL,
    start_date          DATE         NOT NULL,
    end_date            DATE         NOT NULL,
    planned_uplift_pct  DECIMAL(5,3) NOT NULL COMMENT 'Expected demand lift e.g. 0.25 = 25%',
    actual_uplift_pct   DECIMAL(5,3)           COMMENT 'Measured post-event; NULL if future/active',
    regions             TEXT         NOT NULL   COMMENT 'Comma-separated location_ids or ALL',
    target_atc_codes    VARCHAR(200)            COMMENT 'Comma-separated ATC codes targeted',
    status              VARCHAR(20)  NOT NULL DEFAULT 'planned' COMMENT 'planned | active | completed | cancelled',
    created_by          VARCHAR(100)            COMMENT 'e.g. marketing_team@pharma.in',
    approved_on         DATE,
    created_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (id),
    INDEX idx_promo_id (promo_id),
    INDEX idx_dates (start_date, end_date),
    INDEX idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Marketing promo calendar with planned and actual uplifts';


-- =============================================================
-- [INPUT-ROLLING] 6. demand_history
-- Daily sales per SKU per region. Core ML training input. Grows daily.
-- =============================================================
CREATE TABLE demand_history (
    id          BIGINT      NOT NULL AUTO_INCREMENT,
    date        DATE        NOT NULL,
    sku_id      VARCHAR(20) NOT NULL COMMENT 'FK → sku_master.sku_id',
    atc_code    VARCHAR(10) NOT NULL COMMENT 'Denormalized for query speed',
    region      VARCHAR(30) NOT NULL COMMENT 'FK → locations.location_id',
    units       INT         NOT NULL DEFAULT 0,
    ingested_at TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (id),
    UNIQUE KEY uq_demand (date, sku_id, region),
    INDEX idx_date (date),
    INDEX idx_sku_region (sku_id, region),
    INDEX idx_atc_date (atc_code, date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Daily sales history — primary ML training data';


-- =============================================================
-- [INPUT-ROLLING] 7. disease_burden_index
-- Daily ILI/flu burden per region. Sourced from public health APIs.
-- (Previously flu_index — renamed and enriched with source metadata)
-- =============================================================
CREATE TABLE disease_burden_index (
    id              BIGINT       NOT NULL AUTO_INCREMENT,
    record_date     DATE         NOT NULL,
    region          VARCHAR(30)  NOT NULL COMMENT 'FK → locations.location_id',
    index_value     DECIMAL(8,2) NOT NULL COMMENT 'ILI burden score',
    index_type      VARCHAR(30)  NOT NULL DEFAULT 'ili' COMMENT 'ili = Influenza-Like Illness',
    source          VARCHAR(100) NOT NULL DEFAULT 'IDSP_State_Surveillance'
                    COMMENT 'Data source e.g. IDSP_State_Surveillance, WHO_GISRS',
    source_lag_days TINYINT      NOT NULL DEFAULT 3
                    COMMENT 'Typical days between actual date and data availability',
    ingested_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (id),
    UNIQUE KEY uq_dbi (record_date, region),
    INDEX idx_region_date (region, record_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
COMMENT='Daily disease burden index per region — sourced from public health surveillance';


-- =============================================================
-- [INPUT-ROLLING] 8. inventory_batches
-- On-hand inventory snapshot per batch. New snapshot rows each day.
-- Use as_of_date to filter to latest state.
-- =============================================================
CREATE TABLE inventory_batches (
    id              BIGINT      NOT NULL AUTO_INCREMENT,
    as_of_date      DATE        NOT NULL COMMENT 'Snapshot date',
    batch_id        VARCHAR(20) NOT NULL COMMENT 'e.g. B00001',
    sku_id          VARCHAR(20) NOT NULL COMMENT 'FK → sku_master.sku_id',
    location        VARCHAR(30) NOT NULL COMMENT 'FK → locations.location_id',
    qty_units       INT         NOT NULL DEFAULT 0,
    expiry_date     DATE        NOT NULL,
    received_date   DATE        NOT NULL,
    unit_cost_inr   INT         NOT NULL,
    status          VARCHAR(30) NOT NULL COMMENT 'healthy | watch | near_expiry_risk | stockout',
    grn_number      VARCHAR(50)          COMMENT 'Goods Receipt Note reference',
    created_at      TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (id),
    INDEX idx_snapshot (as_of_date, location),
    INDEX idx_sku_loc (sku_id, location),
    INDEX idx_expiry (expiry_date),
    INDEX idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Daily inventory batch snapshots';


-- =============================================================
-- [INPUT-ROLLING] 9. distributor_orders
-- Actual historical orders placed by each distributor over time.
-- Captures real ordering patterns: cycle compliance, order size variance,
-- partial fulfillments. This is what "distributor order patterns" means.
-- Populated by: daily ingest of distributor PO data.
-- =============================================================
CREATE TABLE distributor_orders (
    id                    BIGINT        NOT NULL AUTO_INCREMENT,
    order_id              VARCHAR(40)   NOT NULL COMMENT 'Distributor PO reference number',
    distributor_id        VARCHAR(30)   NOT NULL COMMENT 'FK → distributors.distributor_id',
    region                VARCHAR(30)   NOT NULL COMMENT 'FK → locations.location_id',
    sku_id                VARCHAR(20)   NOT NULL COMMENT 'FK → sku_master.sku_id',
    atc_code              VARCHAR(10)   NOT NULL COMMENT 'Denormalized for query speed',
    order_date            DATE          NOT NULL COMMENT 'Date PO was raised by distributor',
    expected_delivery     DATE                   COMMENT 'Promised delivery date',
    actual_delivery       DATE                   COMMENT 'Actual delivery date (NULL if pending)',
    ordered_qty           INT           NOT NULL COMMENT 'Units ordered',
    fulfilled_qty         INT           NOT NULL DEFAULT 0 COMMENT 'Units actually delivered',
    unit_cost_inr         INT           NOT NULL COMMENT 'Cost at time of order',
    order_value_inr       INT           NOT NULL COMMENT 'ordered_qty × unit_cost_inr',
    days_since_last_order INT                    COMMENT 'Actual cycle length — shows ordering pattern',
    fulfillment_status    VARCHAR(20)   NOT NULL DEFAULT 'pending'
                          COMMENT 'pending | partial | fulfilled | cancelled',
    shortfall_qty         INT           NOT NULL DEFAULT 0
                          COMMENT 'ordered_qty − fulfilled_qty; 0 if fully served',
    ingested_at           TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (id),
    UNIQUE KEY uq_order (order_id, sku_id),
    INDEX idx_distributor (distributor_id),
    INDEX idx_region_date (region, order_date),
    INDEX idx_sku_date (sku_id, order_date),
    INDEX idx_status (fulfillment_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
COMMENT='Historical distributor orders — captures real ordering patterns, cycle times and fulfillment rates';


-- =============================================================
-- [INPUT-ROLLING] 10. warehouse_capacity_log
-- Weekly snapshot of warehouse capacity utilization per location.
-- The static capacity_units in locations table shows max capacity.
-- This table shows how utilization changed over time — vital for
-- "Warehouse Capacity" dashboard charts and capacity planning.
-- Populated by: weekly aggregation from inventory_batches.
-- =============================================================
CREATE TABLE warehouse_capacity_log (
    id               BIGINT        NOT NULL AUTO_INCREMENT,
    snapshot_date    DATE          NOT NULL COMMENT 'Date of this capacity reading (weekly)',
    location_id      VARCHAR(30)   NOT NULL COMMENT 'FK → locations.location_id',
    capacity_units   INT           NOT NULL COMMENT 'Max capacity at this location on this date',
    used_units       INT           NOT NULL COMMENT 'Total units on hand (sum of inventory_batches.qty_units)',
    available_units  INT           NOT NULL COMMENT 'capacity_units − used_units',
    utilization_pct  DECIMAL(5,2)  NOT NULL COMMENT 'used / capacity × 100',
    near_expiry_units INT          NOT NULL DEFAULT 0
                     COMMENT 'Units expiring within 90 days (risk flag)',
    sku_count        INT           NOT NULL DEFAULT 0
                     COMMENT 'Number of distinct SKUs stored at this location',
    computed_at      TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (id),
    UNIQUE KEY uq_capacity (snapshot_date, location_id),
    INDEX idx_location_date (location_id, snapshot_date),
    INDEX idx_utilization (utilization_pct)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
COMMENT='Weekly warehouse capacity utilization history — shows how storage load evolved over time';


-- =============================================================
-- [DERIVED] 11. sku_market_share_monthly
-- Brand share within ATC category, computed monthly from demand_history.
-- Replaces the static category_share field that was in sku_master.
-- =============================================================
CREATE TABLE sku_market_share_monthly (
    id                  BIGINT       NOT NULL AUTO_INCREMENT,
    sku_id              VARCHAR(20)  NOT NULL COMMENT 'FK → sku_master.sku_id',
    atc_code            VARCHAR(10)  NOT NULL,
    period_year         SMALLINT     NOT NULL COMMENT 'e.g. 2018',
    period_month        TINYINT      NOT NULL COMMENT '1–12',
    total_units_sold    INT          NOT NULL COMMENT 'Units of this SKU in the month',
    category_units_sold INT          NOT NULL COMMENT 'Total units of the ATC category',
    market_share        DECIMAL(6,4) NOT NULL COMMENT 'sku_units / category_units',
    computed_on         DATE         NOT NULL COMMENT 'When analytics ran this aggregation',

    PRIMARY KEY (id),
    UNIQUE KEY uq_sku_period (sku_id, period_year, period_month),
    INDEX idx_atc_period (atc_code, period_year, period_month)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
COMMENT='Monthly brand market share computed from actual sales — organically drifts over time';


-- =============================================================
-- [DERIVED] 12. location_demand_summary
-- Quarterly regional demand contribution computed from demand_history.
-- Replaces the static demand_share field that was in locations.
-- =============================================================
CREATE TABLE location_demand_summary (
    id              BIGINT       NOT NULL AUTO_INCREMENT,
    location_id     VARCHAR(30)  NOT NULL COMMENT 'FK → locations.location_id',
    period_year     SMALLINT     NOT NULL,
    period_quarter  TINYINT      NOT NULL COMMENT '1 | 2 | 3 | 4',
    total_units     INT          NOT NULL COMMENT 'Total units from this location in the quarter',
    national_share  DECIMAL(6,4) NOT NULL COMMENT 'This location / all locations',
    yoy_growth_pct  DECIMAL(7,2)           COMMENT 'Year-over-year growth % vs same quarter prior year',
    computed_on     DATE         NOT NULL,

    PRIMARY KEY (id),
    UNIQUE KEY uq_loc_period (location_id, period_year, period_quarter),
    INDEX idx_year_quarter (period_year, period_quarter)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
COMMENT='Quarterly regional demand share — computed from demand_history, shows organic demand drift';


-- =============================================================
-- [DERIVED] 13. sku_cost_history
-- Full cost timeline per SKU. Real costs change every 1–2 years.
-- =============================================================
CREATE TABLE sku_cost_history (
    id              BIGINT       NOT NULL AUTO_INCREMENT,
    sku_id          VARCHAR(20)  NOT NULL COMMENT 'FK → sku_master.sku_id',
    unit_cost_inr   INT          NOT NULL,
    effective_from  DATE         NOT NULL,
    effective_to    DATE                   COMMENT 'NULL = currently active',
    reason          VARCHAR(200)           COMMENT 'e.g. Annual supplier renegotiation, GST transition',
    approved_by     VARCHAR(100)           COMMENT 'e.g. procurement@pharma.in',
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (id),
    INDEX idx_sku_cost (sku_id, effective_from),
    INDEX idx_active (sku_id, effective_to)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
COMMENT='SKU cost timeline — costs change with supplier negotiations and regulatory revisions';


-- =============================================================
-- [OUTPUT] 14. forecasts_final
-- ML ensemble forecast per SKU, region, horizon. One batch per daily run.
-- =============================================================
CREATE TABLE forecasts_final (
    id               BIGINT        NOT NULL AUTO_INCREMENT,
    as_of_date       DATE          NOT NULL COMMENT 'Date the forecast was generated',
    sku_id           VARCHAR(20)   NOT NULL,
    atc_code         VARCHAR(10)   NOT NULL COMMENT 'Denormalized',
    region           VARCHAR(30)   NOT NULL,
    forecast_date    DATE          NOT NULL COMMENT 'Future date being predicted',
    horizon          INT           NOT NULL COMMENT 'Days ahead (1–42)',
    p10              DECIMAL(12,2) NOT NULL COMMENT '10th percentile forecast',
    p50              DECIMAL(12,2) NOT NULL COMMENT 'Median forecast',
    p90              DECIMAL(12,2) NOT NULL COMMENT '90th percentile forecast',
    momentum_u       DECIMAL(10,4)           COMMENT 'Recent demand momentum ratio',
    flu_ratio        DECIMAL(8,4)            COMMENT 'ILI index ratio vs 14 days prior',
    sense_adjustment DECIMAL(8,4)            COMMENT 'Total sensing uplift applied',
    models_used      VARCHAR(100)            COMMENT 'e.g. lgbm,chronos',
    lgbm_weight      DECIMAL(5,3),
    chronos_weight   DECIMAL(5,3),
    created_at       TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (id),
    UNIQUE KEY uq_forecast (as_of_date, sku_id, region, forecast_date),
    INDEX idx_as_of (as_of_date),
    INDEX idx_sku_region (sku_id, region),
    INDEX idx_forecast_date (forecast_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='ML ensemble demand forecasts — one batch per daily rollover run';


-- =============================================================
-- [OUTPUT] 15. replenishment_orders
-- Computed reorder plan per SKU per region. Generated by replenishment.py.
-- =============================================================
CREATE TABLE replenishment_orders (
    id                     BIGINT        NOT NULL AUTO_INCREMENT,
    as_of_date             DATE          NOT NULL,
    sku_id                 VARCHAR(20)   NOT NULL,
    region                 VARCHAR(30)   NOT NULL,
    criticality            VARCHAR(20)   NOT NULL,
    lead_time_days         INT           NOT NULL,
    service_level          DECIMAL(4,2)  NOT NULL COMMENT 'e.g. 0.99',
    mu_daily               DECIMAL(10,2) NOT NULL COMMENT 'Mean daily demand from forecast',
    sigma_daily            DECIMAL(10,2) NOT NULL COMMENT 'Std dev of daily demand',
    safety_stock           INT           NOT NULL,
    target_position        INT           NOT NULL,
    on_hand                INT           NOT NULL,
    order_qty              INT           NOT NULL,
    order_value_inr        INT           NOT NULL,
    days_of_supply_on_hand DECIMAL(8,2)           COMMENT 'NULL if stockout',
    status                 VARCHAR(30)   NOT NULL COMMENT 'ok | low | stockout_risk',
    created_at             TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (id),
    UNIQUE KEY uq_repl (as_of_date, sku_id, region),
    INDEX idx_as_of (as_of_date),
    INDEX idx_status (status),
    INDEX idx_criticality (criticality)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Daily replenishment order plan';


-- =============================================================
-- [OUTPUT] 16. transfer_plan
-- Intra-network transfer recommendations. Generated by allocation.py.
-- =============================================================
CREATE TABLE transfer_plan (
    id                        BIGINT       NOT NULL AUTO_INCREMENT,
    as_of_date                DATE         NOT NULL,
    batch_id                  VARCHAR(20)            COMMENT 'Source inventory batch',
    sku_id                    VARCHAR(20)  NOT NULL,
    from_location             VARCHAR(30)  NOT NULL,
    to_location               VARCHAR(30)  NOT NULL,
    qty_units                 INT          NOT NULL,
    expiry_date               DATE,
    days_to_expiry            INT,
    transfer_lead_days        INT          NOT NULL,
    value_saved_inr           INT          NOT NULL DEFAULT 0,
    reason                    VARCHAR(30)  NOT NULL COMMENT 'expiry_rescue | shortage_rescue',
    src_days_of_supply_before DECIMAL(8,2)           COMMENT 'Source DOS before this transfer',
    created_at                TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (id),
    INDEX idx_as_of (as_of_date),
    INDEX idx_sku (sku_id),
    INDEX idx_from_to (from_location, to_location),
    INDEX idx_reason (reason)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Stock transfer recommendations to prevent expiry and resolve shortages';


-- =============================================================
-- [OUTPUT] 17. writeoff_risk
-- Batches at risk of write-off after transfer plan applied. Generated by allocation.py.
-- =============================================================
CREATE TABLE writeoff_risk (
    id                      BIGINT       NOT NULL AUTO_INCREMENT,
    as_of_date              DATE         NOT NULL,
    batch_id                VARCHAR(20)  NOT NULL,
    sku_id                  VARCHAR(20)  NOT NULL,
    location                VARCHAR(30)  NOT NULL,
    qty_units               INT          NOT NULL,
    leftover                INT          NOT NULL COMMENT 'Units likely unsold before expiry',
    residual_writeoff_units INT          NOT NULL COMMENT 'Units that will be written off post-transfers',
    unit_cost_inr           INT          NOT NULL,
    residual_value_inr      INT          NOT NULL COMMENT 'INR financial loss',
    expiry_date             DATE         NOT NULL,
    days_to_expiry          INT          NOT NULL,
    created_at              TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (id),
    INDEX idx_as_of (as_of_date),
    INDEX idx_sku_loc (sku_id, location),
    INDEX idx_expiry (expiry_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Residual expiry write-off risk after transfer plan optimization';


-- =============================================================
-- [OUTPUT] 18. simulation_daily
-- Day-by-day simulation log for proposed vs status_quo policy.
-- Generated by simulate.py. Large table — index carefully.
-- =============================================================
CREATE TABLE simulation_daily (
    id                  BIGINT        NOT NULL AUTO_INCREMENT,
    as_of_date          DATE          NOT NULL COMMENT 'Simulation run date',
    policy              VARCHAR(20)   NOT NULL COMMENT 'proposed | status_quo',
    date                DATE          NOT NULL COMMENT 'Simulated calendar date',
    sku_id              VARCHAR(20)   NOT NULL,
    region              VARCHAR(30)   NOT NULL,
    criticality         VARCHAR(20)   NOT NULL,
    demand              DECIMAL(12,2) NOT NULL,
    fulfilled           DECIMAL(12,2) NOT NULL,
    unfulfilled         DECIMAL(12,2) NOT NULL DEFAULT 0,
    expired_units       DECIMAL(12,2) NOT NULL DEFAULT 0,
    expired_value_inr   DECIMAL(14,2) NOT NULL DEFAULT 0,
    ending_inventory    DECIMAL(12,2) NOT NULL DEFAULT 0,
    created_at          TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (id),
    INDEX idx_run (as_of_date, policy),
    INDEX idx_date_region (date, region),
    INDEX idx_sku (sku_id),
    INDEX idx_criticality (criticality)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Daily simulation log for policy comparison';


-- =============================================================
-- [OUTPUT] 19. kpi_summary
-- High-level KPIs per policy per run. Generated by simulate.py.
-- =============================================================
CREATE TABLE kpi_summary (
    id                           BIGINT       NOT NULL AUTO_INCREMENT,
    as_of_date                   DATE         NOT NULL,
    policy                       VARCHAR(20)  NOT NULL COMMENT 'proposed | status_quo',
    fill_rate_pct                DECIMAL(6,2) NOT NULL,
    critical_fill_rate_pct       DECIMAL(6,2) NOT NULL,
    stockout_units               INT          NOT NULL DEFAULT 0,
    critical_stockout_sitedays   INT          NOT NULL DEFAULT 0,
    writeoff_value_inr           BIGINT       NOT NULL DEFAULT 0,
    avg_ending_inventory         DECIMAL(14,2),
    created_at                   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (id),
    UNIQUE KEY uq_kpi (as_of_date, policy),
    INDEX idx_as_of (as_of_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='KPI summary per policy per daily run';


-- =============================================================
-- [OUTPUT] 20. alerts
-- Machine-generated supply chain alerts. Generated by alerts.py.
-- is_acknowledged allows frontend to track user actions.
-- =============================================================
CREATE TABLE alerts (
    id                BIGINT       NOT NULL AUTO_INCREMENT,
    as_of_date        DATE         NOT NULL,
    severity          VARCHAR(10)  NOT NULL COMMENT 'RED | AMBER',
    type              VARCHAR(50)  NOT NULL COMMENT 'shortage_risk | expiry_writeoff_risk | demand_surge_detected',
    sku_id            VARCHAR(20)  NOT NULL COMMENT '* for region-wide alerts',
    region            VARCHAR(30)  NOT NULL,
    facts             JSON                   COMMENT 'Alert-specific metrics (days_of_supply, units_at_risk, etc.)',
    action            TEXT                   COMMENT 'Recommended action text',
    is_acknowledged   BOOLEAN      NOT NULL DEFAULT FALSE,
    acknowledged_by   VARCHAR(100),
    acknowledged_at   TIMESTAMP,
    created_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (id),
    INDEX idx_as_of (as_of_date),
    INDEX idx_severity (severity),
    INDEX idx_type (type),
    INDEX idx_unacknowledged (as_of_date, is_acknowledged)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Actionable supply chain alerts';


-- =============================================================
-- [OUTPUT] 21. alert_digest
-- AI-generated (Gemma/LLM) daily narrative for CSCO.
-- One digest per day.
-- =============================================================
CREATE TABLE alert_digest (
    id               BIGINT       NOT NULL AUTO_INCREMENT,
    as_of_date       DATE         NOT NULL,
    review_mode      VARCHAR(30)  NOT NULL COMMENT 'WEEKLY_STANDARD | DAILY_SURGE_MODE',
    surge_regions    TEXT                   COMMENT 'Comma-separated regions in demand surge',
    red_alert_count  INT          NOT NULL DEFAULT 0,
    digest_text      TEXT         NOT NULL COMMENT 'Full LLM narrative for the CSCO',
    model_used       VARCHAR(50)            COMMENT 'e.g. gemma4:e2b | template_fallback',
    created_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (id),
    UNIQUE KEY uq_digest_date (as_of_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Daily AI-generated escalation brief for Chief Supply Chain Officer';


-- =============================================================
-- [OUTPUT] 22. rolling_run_log
-- Audit trail of every daily pipeline execution.
-- =============================================================
CREATE TABLE rolling_run_log (
    id                    BIGINT       NOT NULL AUTO_INCREMENT,
    as_of_date            DATE         NOT NULL,
    previous_as_of_date   DATE,
    models_used           VARCHAR(100)           COMMENT 'e.g. lgbm,chronos',
    lgbm_weight           DECIMAL(5,3),
    chronos_weight        DECIMAL(5,3),
    wmape                 DECIMAL(8,4)           COMMENT 'Realized WMAPE vs actuals (NULL if no actuals yet)',
    forecast_rows         INT,
    status                VARCHAR(20)  NOT NULL DEFAULT 'success' COMMENT 'success | partial | failed',
    error_message         TEXT,
    run_duration_seconds  INT,
    triggered_by          VARCHAR(50)  NOT NULL DEFAULT 'cron' COMMENT 'cron | manual | api',
    created_at            TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (id),
    UNIQUE KEY uq_run_date (as_of_date),
    INDEX idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Audit trail of every daily rollover pipeline run';
